<?php
$_product = $this->getData('product');
if($this->getCashbackPercent()){
?>

<div class="products-list-ame-info">
    <img src="<?php echo $this->getSkinUrl('images/ame/ame-logo.png'); ?>" width="45" style="display: inline;">
    <span class="product-list-ame-text" style="color: #5f5f5f;"> receba</span>
    <span class="product-list-ame-value" style="color: #f6235e; font-size: 15px">
        R$<?php echo number_format($this->getCashbackValue($_product),2,",","."); ?>
    </span>
    <span class="product-list-ame-text" style="color: #1b0487;">
        (<?php echo $this->getCashbackPercent(); ?>% de volta)
    </span>
</div>
<?php
}
?>
